export const terms = {
  username: 'שם משתמש',
  signIn: 'כניסה',
  confirmPassword: 'אימות סיסמה',
  signUp: 'הרשמה',
  doesNotMatchPassword: 'לא תואם לסיסמה',
  password: 'סיסמה',
  updateInfo: 'עדכון פרטים',
  changePassword: 'שינוי סיסמה',
  hello: 'שלום',
  invalidOperation: 'פעולה לא חוקית',
  admin: 'אדמין',
  manager: 'מנהל',
  disabled: 'לא פעיל',
  yes: 'כן',
  no: 'לא',
  ok: 'אישור',
  areYouSureYouWouldLikeToDelete: 'האם ברצונך למחוק את',
  cancel: 'ביטול',
  close: 'סגור',
  home: 'דף הבית',
  userAccounts: 'משתמשים',
  invalidSignIn: 'פרטי התחברות שגויים',
  signOut: 'יציאה',
  resetPassword: 'איפוס סיסמה',
  passwordDeletedSuccessful: 'הסיסמה נמחקה בהצלחה',
  passwordDeleteConfirmOf: 'האם ברצונך למחוק את הסיסמה של',
  rememberOnThisDevice: 'זכור אותי במכשיר זה',
  RTL: true,
  requiredFiled: 'שדה חובה',
  uniqueFiled: 'קיים כבר',
  createDate: 'תאריך יצירה',

  // Projects module
  projects: 'פרויקטים',
  project: 'פרויקט',
  projectName: 'שם פרויקט',
  projectDescription: 'תיאור',
  projectLocation: 'מיקום',
  addProject: 'הוסף פרויקט',

  // Buildings module
  buildings: 'בניינים',
  building: 'בניין',
  block: 'גוש',
  plot: 'חלקה',
  subPlot: 'תת-חלקה',
  addBuilding: 'הוסף בניין',

  // Apartments module
  apartments: 'דירות',
  apartment: 'דירה',
  floor: 'קומה',
  propertyType: 'סוג נכס',
  apartmentSize: 'גודל דירה',
  addApartment: 'הוסף דירה',

  // Tenants module
  tenants: 'דיירים',
  tenant: 'דייר',
  firstName: 'שם פרטי',
  lastName: 'שם משפחה',
  idNumber: 'תעודת זהות',
  mobile: 'נייד',
  additionalPhone: 'טלפון נוסף',
  isRepresentative: 'נציג',
  isCommitteeMember: 'ועד',
  isElderly: 'אוכלוסייה מבוגרת/מוגבלת',
  actualAddress: 'כתובת מגורים בפועל',
  tenantStatus: 'סטטוס',
  propertyPercentage: 'אחוז בנכס',
  notes: 'הערות',
  addTenant: 'הוסף דייר',

  // Messages module
  messages: 'הודעות',
  message: 'הודעה',
  messageText: 'טקסט הודעה',
  attachedFiles: 'קבצים מצורפים',
  recipientIds: 'נמענים',
  sendStatus: 'סטטוס שליחה',
  sentDate: 'תאריך שליחה',
  sendMessage: 'שלח הודעה',

  // Customers module
  customers: 'לקוחות',
  customer: 'לקוח',
  customerName: 'שם לקוח',
  customerId: 'לקוח',
  email: 'אימייל',
  address: 'כתובת',

  // Contacts module
  contacts: 'אנשי קשר',
  contact: 'איש קשר',
  contactName: 'שם איש קשר',
  contactMobile: 'נייד איש קשר',
  isDefaultContact: 'ברירת מחדל',

  // Service Calls module
  serviceCalls: 'קריאות שירות',
  serviceCall: 'קריאת שירות',
  callNumber: 'מספר קריאה',
  site: 'אתר',
  description: 'תיאור הקריאה',
  status: 'סטטוס',
  serviceCallType: 'סוג שירות',
  lastUpdateDate: 'עדכון אחרון',

  // WhatsApp module
  whatsapp: 'ווטסאפ',
  whatsappDashboard: 'לוח בקרה - ווטסאפ',
  whatsappPhone: 'מספר טלפון',
  whatsappCustomerId: 'לקוח',
  whatsappCustomerName: 'שם לקוח',
  whatsappMessageText: 'תוכן הודעה',
  whatsappMessageType: 'סוג הודעה',
  whatsappMessageStatus: 'סטטוס הודעה',
  whatsappRelatedServiceCallId: 'קריאת שירות קשורה',
  whatsappRelatedMessageId: 'הודעה קשורה',
  whatsappLogType: 'סוג אירוע',
  whatsappLogDetails: 'פרטים',
  whatsappPendingMessages: 'הודעות ממתינות',
  whatsappOpenServiceCalls: 'קריאות פתוחות',
  whatsappTodayMessages: 'הודעות היום',
  whatsappTodayServiceCalls: 'קריאות היום',
  whatsappActivityLog: 'יומן פעילות'
}